 --DDL : DATA DEFINITION LANG.
 --GREATE/ALTER/DROP/TRUNCATE
CREATE TABLE TEST1
(U_ID VARCHAR2(10),
U_DATE DATE);

DESC TEST1;
SELECT * FROM TEST1;

DESC STUDENT;
DESC EMP;

CREATE TABLE STUDENT2
(STU_NO CHAR(9),
STU_NAME VARCHAR2(20),
STU_DEPT VARCHAR2(20),
STU_CRADE NUMBER(1),
STU_CLASS CHAR(1),
STU_GENDER CHAR(1),
STU_HEIGHT NUMBER(5,2),
STU_WEIGHT NUMBER(5,2));

DESC STUDENT2;

-- 기존의 테이블을 이용해서 새로운 테이블을 만드는 방법
CREATE TABLE T_STUDENT
AS 
SELECT *
FROM STUDENT
WHERE STU_DEPT = '기계';

SELECT * FROM T_STUDENT;

--ALTER()
ALTER TABLE T_STUDENT
ADD (ARMY CHAR(1));
DESC T_STUDENT;
SELECT * FROM T_STUDENT;

ALTER TABLE T_STUDENT
MODIFY (ARMY NUMBER);

RENAME T_STUDENT TO TEST_STUDENT;
DESC TEST_STUDENT;

--테이블을 완전삭제명령어는 DROP
DROP TABLE TEST_STUDENT;

--CONSTRAINTS : NOT NULL
CREATE TABLE T_STUDENT(
STU_NO CHAR(9),
STU_NAME VARCHAR2(20),
STU_DEPT VARCHAR2(20)
CONSTRAINT N_STU_DEPT NOT NULL,
STU_GRADE NUMBER(1),
STU_HEIGHT NUMBER(5,2));

-- 제약어를 모니터하는 방법
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_STUDENT';

DROP TABLE T_STUDENT;

--DONSTRAINTS: UNIQUE

CREATE TABLE T_STUDENT(
STU_NO CHAR(9),
STU_NAME VARCHAR2(12)
CONSTRAINT U_STU_NAME UNIQUE,
STU_DEPT VARCHAR2(20)
CONSTRAINT S_STU_DEPT NOT NULL,
STU_WEIGHT NUMBER(5,2));

SELECT * 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_STUDENT';

DROP TABLE T_STUDENT;

CREATE TABLE T_STUDENT
(STU_NO CHAR(9),
STU_NAME VARCHAR2(12)
CONSTRAINT U_STU_NAME UNIQUE,
STU_DEPT VARCHAR(20)
CONSTRAINT N_STU_DEPT NOT NULL,
STU_CRADE NUMBER(1),
STU_WEIGHT NUMBER(5,2),
CONSTRAINT P_STU_NO PRIMARY KEY(STU_NO));   --STU_NO 옆에 PRIMARY KEY 적어도 되지만 마지막에 지정해줘도 됨

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_STUDENT';

-- CONSTRAINT : FOREIGN KEY
CREATE TABLE T_ENROL(
SUB_NO CHAR(3),
STU_NO NUMBER(9),
ENR_GRADE NUMBER(3),
CONSTRAINT ENR_PK1 PRIMARY KEY (SUB_NO, STU_NO));
 
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_ENROL';

-- CONSTRAINT : CHECK...
CREATE TABLE T_STUDENT(
STU_NO CHAR(9),
STU_NAME VARCHAR2(12)
CONSTRAINT U_STU_NAME UNIQUE,
STU_DEPT VARCHAR(10)
CONSTRAINT N_STU_DEPT NOT NULL,
STU_GRADE NUMBER(1),
STU_GENDER CHAR(1)
CONSTRAINT C_STU_GENDER CHECK(STU_GENDER IN ('M','F')),  -- M과 F로만 나올 수 있도록
STU_WEIGHT NUMBER(5,2),
CONSTRAINT P_STU_NO PRIMARY KEY(STU_NO));
 
SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_STUDENT';

-- VIEW의 용도와 생성하는 방법
CREATE OR REPLACE VIEW V_STUDENT1
AS
SELECT * FROM STUDENT WHERE STU_DEPT='컴퓨터정보';

SELECT * FROM V_STUDENT1;

CREATE OR REPLACE VIEW V_ENROL1
AS
SELECT SUB_NAME, A.SUB_NO,STU_NO, ENR_GRADE
FROM ENROL A, SUBJECT B
WHERE A.SUB_NO = B.SUB_NO;

SELECT * FROM V_ENROL1;
 
CREATE INDEX I_STU_NAME ON STUDENT(STU_NAME);
CREATE INDEX I_STU_NO_NAME ON STUDENT(STU_NO, STU_NAME);
 
SELECT * FROM USER_INDEXES
WHERE TABLE_NAME = 'STUDENT';

-- SEQUENCE
CREATE SEQUENCE SEQ1
INCREMENT BY 2
START WITH 1000
MAXVALUE 2000;

SELECT SEQ1.NEXTVAL FROM DUAL;
 
 
 
 
 