 SELECT TABLE_NAME
 FROM USER_TABLES;
 
 -- DML .. INSERT/UPDATE/DELETE
DROP TABLE A_ENROL;

 CREATE TABLE A_ENROL
 AS
 SELECT *
 FROM ENROL
 WHERE STU_NO < 20150000;
 
 --INSERT
 INSERT INTO A_ENROL(SUB_NO, STU_NO, ENR_GRADE)    -- 명시적 방법
 VALUES (108, 20151062, 92);
 
 DESC A_ENROL;
 SELECT * FROM A_ENROL;
 
 INSERT INTO A_ENROL VALUES (111, 20153075, NULL);   -- 임의적 방법
 
 INSERT INTO A_ENROL(SUB_NO, STU_NO)
 VALUES (110, 20152088);
 
 --복수형삽입경우
 SELECT * FROM A_ENROL;
 SELECT * FROM A_ENROL
 WHERE STU_NO LIKE '2015%';
 
 INSERT INTO A_ENROL
 SELECT * FROM ENROL
 WHERE STU_NO LIKE '2015%'; 
 
 SELECT * FROM A_ENROL;
 -- UPDATE
 UPDATE A_ENROL
 SET ENR_GRADE = ENR_GRADE + 5;
 SELECT * FROM A_ENROL;
 
 --과목번호 101에 대해서 5점을 추가하라
 UPDATE A_ENROL
 SET ENR_GRADE = ENR_GRADE + 5
 WHERE SUB_NO = 101;
 
 -- 과목이름이 시스템분석설계인 학생에 대해서만 점수를 10점을 올려라
SELECT * FROM SUBJECT;
SELECT * FROM A_ENROL;
UPDATE A_ENROL
SET ENR_GRADE = ENR_GRADE+10
WHERE SUB_NO = (SELECT SUB_NO
                FROM SUBJECT
                WHERE SUB_NAME = '시스템분석설계');


 -- DELETE
 DELETE FROM A_ENROL
 WHERE STU_NO = 20131001;
 
 SELECT * FROM A_ENROL;
 
 -- 과목이름이 기계요소설계인 과목을 수강하는 학생의 수강테이블(ENROL)을 지워라
 DELETE FROM A_ENROL
 WHERE SUB_NO = (SELECT SUB_NO
                FROM SUBJECT
                WHERE SUB_NAME = '기계요소설계');

SELECT * FROM A_ENROL;

DELETE FROM A_ENROL;
SELECT * FROM A_ENROL;

ROLLBACK;
SELECT * FROM A_ENROL;

-- TCL(TRANSACTION COUNTROL LANG,)__COMIT/ROLLBACK
SELECT * FROM B_STUDENT;
DELETE FROM B_STUDENT;
SELECT * FROM B_STUDENT;
ROLLBACK;
SELECT * FROM B_STUDENT;

CREATE TABLE C_STUDENT       -- DDL을 하게되면 자동으로 COMMIT하게 됨
(STU_NO NUMBER,
STT_ANE CHAR(10));

ROLLBACK;
SELECT * FROM B_STUDENT;
SELECT * FROM A_STUDENT;
SELECT * FROM A_STUDENT;
SELECT * FROM A_STUDENT;
ROLLBACK;
SELECT * FROM A_STUDENT;

INSERT INTO A_STUDENT(STU_NO, STU_NAME)
VALUES(10,'홍');
SELECT * FROM A_STUDENT;

-- CMD에서 SQLPLUS SCOTT/비번 입력  --> 홍 추가된것 나오지 않음

COMMIT;

 -- CMD에서 SQLPLUS SCOTT/비번 입력  --> 홍 추가된건 나옴 (COMMIT을 했으므로)
 
 
 
 